### ISSUE TITLE
Add Terms & Conditions checkbox to Login, make required

### ISSUE THREAD

**Issue by dmitrizagidulin** [xrchat/kxr-dev#20]
1. Add a [ ] I agree to the [Terms & Conditions]() checkbox to the magic link Login screen. Make it required. 
2. Link it to a static Terms & Conditions page (this is going to be provided by customer).

**Comment by dmitrizagidulin** [comment]
@green9016 - the two links will be loaded from config (client config is fine). And should default to `/privacy-policy`, and `/terms-of-service`.

**Comment by green9016** [comment]
Hello @dmitrizagidulin @shawticus 
I made a mistake while pushing code. I pushed the changes of this issue to the master branch.
https://github.com/xrchat/xrchat-client/commit/5074ffa96c7f614b7f164c6cff87592a5d9ae544
This is my commit.

**Comment by dmitrizagidulin** [comment]
Implemented and deployed to dev server in https://github.com/xrchat/xrchat-client/commit/5074ffa96c7f614b7f164c6cff87592a5d9ae544. Closing.
