### ISSUE TITLE
Remove Gaze Select, Add Tap To Select Video

### ISSUE THREAD

**Issue by thatpassesfor** [xrchat/kxr-dev#22]
As a new user when I enter the video gallery landing page, it is not obvious how to select a video.  My first impulse, clicking on an icon, has no effect.    From talking to the team, I found out that I was supposed to use the reticule and gaze at a video to select it.  This makes sense for Cardboard viewers, but will confuse new customers who do not have a Cardboard. 

It is also too easy to inadvertently enter a video by gazing around. 

I don't know what the right balance of usability is.  At very least, if we're stuck with reticule as the only input mechanism, we may want to consider displaying instructions to the user.

**Comment by mohrtw** [comment]
I can add mouse controls for desktop and just have the gaze for vr. We just prioritized the gaze controls because Kai was targeting.

I've been planning on opening an issue on client about changing controls based on device. 

Perhaps down the line we can add a tutorial for when a new user first enters the page.

**Comment by dmitrizagidulin** [comment]
@mohrtw perfect, yeah. And, go ahead and open that issue for changing controls (prolly in the -client repo).

**Comment by shawticus** [comment]
Ideal UX for this:
**Phone** -- tap to interact. Hold down (for rotation) is ignored
**VR Headset** -- raycast from controller, no reticle
**GearVR / Google Cardboard** -- reticle shown, raycast from head. "Click" selection activates video, not timed gaze selection.

**Comment by dmitrizagidulin** [comment]
(@mohrtw is working on this currently.)

**Comment by dmitrizagidulin** [comment]
This is now implemented, tested on desktop and mobile. Closing.
