### ISSUE TITLE
Make video/scene thumbnails double-sided (same from the back and the front)

### ISSUE THREAD

**Issue by dmitrizagidulin** [xrchat/kxr-dev#41]
Request from the customer - can the gallery thumbnails (for scenes and videos) be double-sided (that is, if you walk behind the gallery, you want to see the video thumbnails from the back as well (instead of blank rectangles).

**Comment by mohrtw** [comment]
[xrchat-client#146](https://github.com/xrchat/xrchat-client/issues/146) resolved by [xrchat-client#153](https://github.com/xrchat/xrchat-client/pull/153)
